import numpy


def sum_as_string(a: int, b: int) -> str: ...
def sub_as_string(a: int, b: int) -> str: ...
def mult_as_string(a: int, b: int) -> str: ...
def sum_array_as_string(arr: list[int]) -> str: ...
def sum_array_fast(arr: "numpy.ndarray") -> int: ...